### PR TITLE
Readme Updates

### PR DESCRIPTION
**Pull request by pradeexsu**
just simple readme update

### CODE REVIEW

**Comment by pradeexsu** [comment]
hay siddu, please change the repository name after merging this
I suggest a name for this repo "Library Chat Bot Using Python".

**Comment by siddhhu** [comment]
Okay i will change. Thanks for letting me know the name.

**Comment by pradeexsu** [comment]
how is this name "Library-Chat-Bot-Using-NLP-In-Python"
it is more descriptive

**Comment by siddhhu** [comment]
Yes it is preety good if you can change the name change it.

**Comment by pradeexsu** [comment]
bro merge it

**Comment by pradeexsu** [comment]
siddu,please merge it to master branch.
waiting

**Comment by siddhhu** [comment]
Oky will merge tonight

**Pull request merged**
